import React, { useState } from 'react';

const SEOArticle: React.FC = () => {
    const [isExpanded, setIsExpanded] = useState(false);

    const faqData = [
        {
            question: "What is the main difference between pseudo-random and true random numbers?",
            answer: "Pseudo-random numbers are generated by deterministic algorithms and are not truly random, though they appear to be. True random numbers are generated from unpredictable physical phenomena and are non-deterministic, making them suitable for high-security applications."
        },
        {
            question: "Is Math.random() in JavaScript secure for passwords or tokens?",
            answer: "No, `Math.random()` is not cryptographically secure. Its output can be predicted if the seed is known. For any security-sensitive application like generating passwords, tokens, or encryption keys, you must use `crypto.getRandomValues()`."
        },
        {
            question: "Why do games use pseudo-random number generators (PRNGs)?",
            answer: "Games use PRNGs primarily for performance and reproducibility. They are much faster than true random number generators. Additionally, using a specific 'seed' allows developers to recreate the exact same sequence of 'random' events, which is invaluable for debugging and testing game mechanics."
        },
        {
            question: "Can you generate a random integer within a range using `crypto.getRandomValues`?",
            answer: "Yes. `crypto.getRandomValues` generates a random value that can be scaled. You can use the formula `Math.floor(random * (max - min + 1)) + min` to get an integer within a specific range `[min, max]`, just as you would with `Math.random()`."
        },
    ];

    const jsonLdSchema = {
        "@context": "https://schema.org",
        "@graph": [
            {
                "@type": "WebSite",
                "url": "https://rng-app.example.com/",
                "name": "Advanced Random Number Generator",
                "description": "A modern, secure random number generator built with React and TypeScript."
            },
            {
                "@type": "WebApplication",
                "name": "Advanced Random Number Generator",
                "operatingSystem": "All",
                "applicationCategory": "DeveloperApplication",
                "offers": {
                    "@type": "Offer",
                    "price": "0"
                }
            },
            {
                "@type": "Article",
                "mainEntityOfPage": {
                    "@type": "WebPage",
                    "@id": "https://rng-app.example.com/"
                },
                "headline": "The Deep Dive into Random Number Generation: From Gaming to Cryptography",
                "author": {
                    "@type": "Person",
                    "name": "HSINI MOHAMED"
                },
                "publisher": {
                    "@type": "Organization",
                    "name": "Advanced RNG",
                    "logo": {
                        "@type": "ImageObject",
                        "url": "https://rng-app.example.com/favicon.svg"
                    }
                },
                "articleBody": "An extensive guide covering the principles of random number generation, comparing pseudo-randomness with cryptographic security, and exploring their diverse applications in modern technology."
            },
            {
                "@type": "FAQPage",
                "mainEntity": faqData.map(item => ({
                    "@type": "Question",
                    "name": item.question,
                    "acceptedAnswer": {
                        "@type": "Answer",
                        "text": item.answer
                    }
                }))
            }
        ]
    };

    return (
        <section id="seo-article-section" className="w-full max-w-4xl mx-auto bg-gray-900/50 backdrop-blur-lg border border-purple-500/30 rounded-2xl shadow-2xl shadow-purple-900/20 p-6 sm:p-8 text-white">
            <script type="application/ld+json">
                {JSON.stringify(jsonLdSchema)}
            </script>
            <article className="prose prose-invert prose-lg max-w-none text-gray-300 prose-headings:text-purple-400 prose-a:text-pink-400 prose-strong:text-white prose-blockquote:border-l-purple-500">
                <h2 className="text-3xl font-bold text-center !mb-4 bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-pink-500">
                    A Deep Dive into Randomness
                </h2>
                <p className="text-center text-gray-400">
                    Randomness is a concept that is both intuitively understood and profoundly complex. In the digital world, where everything is governed by logic and algorithms, true randomness is an elusive ideal. This guide explores the fascinating world of Random Number Generation (RNG)...
                </p>

                <div className={`transition-all duration-700 ease-in-out overflow-hidden ${isExpanded ? 'max-h-[10000px] opacity-100' : 'max-h-0 opacity-0'}`}>
                    <div className="pt-6">
                        <p>We'll demystify the technology that powers everything from your favorite video game to the secure encryption protecting your financial data. We will delve into the critical differences between standard pseudo-randomness and cryptographic security, uncover the underlying mechanisms, and examine their vast applications.</p>

                        <h2>Table of Contents</h2>
                        <ul>
                            <li>What is a Random Number Generator (RNG)?</li>
                            <li>The Two Flavors of Random: Pseudo-Random vs. True Random</li>
                            <li>Deep Dive: JavaScript's `Math.random()` - The Workhorse PRNG</li>
                            <li>The Security Imperative: `crypto.getRandomValues()`</li>
                            <li>Use Cases and Applications: Where Randomness Reigns</li>
                            <li>Choosing the Right Tool for the Job</li>
                            <li>Conclusion: Embracing Predictable Unpredictability</li>
                            <li>Frequently Asked Questions (FAQ)</li>
                        </ul>

                        <h2>What is a Random Number Generator (RNG)?</h2>
                        <p>At its core, a Random Number Generator is a computational or physical device designed to produce a sequence of numbers or symbols that cannot be reasonably predicted better than by random chance. RNGs are a fundamental building block of modern computing, essential for simulation, sampling, computer games, and, most critically, cryptography.</p>
                        <blockquote>
                        The generation of random numbers is too important to be left to chance. - Robert Coveyou
                        </blockquote>

                        <h2>The Two Flavors of Random: Pseudo-Random vs. True Random</h2>
                        <p>Not all randomness is created equal. The distinction between Pseudo-Random Number Generators (PRNGs) and True Random Number Generators (TRNGs) is paramount, especially when security is a concern.</p>

                        <h3>Pseudo-Random Number Generators (PRNGs)</h3>
                        <p>PRNGs are algorithms that use mathematical formulas to produce sequences of numbers that appear random. A PRNG starts with an initial value called a "seed." The entire sequence of numbers it produces is completely determined by this seed. If you use the same seed, you will get the exact same sequence of numbers every time.</p>
                       
                        <h3>True Random Number Generators (TRNGs)</h3>
                        <p>TRNGs, in contrast, generate numbers from a physical source of entropy—an unpredictable, real-world phenomenon. Examples include atmospheric noise, radioactive decay, or thermal noise. Because the source is inherently unpredictable, the numbers generated are non-deterministic.</p>

                        <h2>Deep Dive: JavaScript's `Math.random()` - The Workhorse PRNG</h2>
                        <p>In web development, `Math.random()` is the most common PRNG. It's fast and sufficient for non-critical tasks like simple animations or basic game mechanics, but it should never be used for security.</p>
                        
                        <h2>The Security Imperative: `crypto.getRandomValues()`</h2>
                        <p>When security matters, modern browsers provide a powerful alternative: `window.crypto.getRandomValues()`. This function is a gateway to the operating system's underlying source of entropy, acting as a TRNG suitable for generating keys, tokens, and anything where unpredictability is a security requirement.</p>

                        <h3>Comparing RNG Use Cases</h3>
                        <div className="overflow-x-auto my-6">
                            <table className="w-full">
                                <thead>
                                    <tr className="border-b border-gray-700">
                                        <th className="text-left p-2">Feature</th>
                                        <th className="text-left p-2">Pseudo-Random (Math.random)</th>
                                        <th className="text-left p-2">Cryptographically Secure (crypto.getRandomValues)</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr className="border-b border-gray-800">
                                        <td className="p-2"><strong>Use Case</strong></td>
                                        <td className="p-2">Gaming, simulations, non-critical randomness</td>
                                        <td className="p-2">Cryptography, security tokens, passwords, lottery</td>
                                    </tr>
                                    <tr className="border-b border-gray-800">
                                        <td className="p-2"><strong>Predictability</strong></td>
                                        <td className="p-2">Predictable if seed is known</td>
                                        <td className="p-2">Unpredictable, non-deterministic</td>
                                    </tr>
                                    <tr className="border-b border-gray-800">
                                        <td className="p-2"><strong>Performance</strong></td>
                                        <td className="p-2">Very Fast</td>
                                        <td className="p-2">Slower, requires system entropy</td>
                                    </tr>
                                    <tr>
                                        <td className="p-2"><strong>Source</strong></td>
                                        <td className="p-2">Deterministic algorithm</td>
                                        <td className="p-2">Physical entropy (hardware noise, etc.)</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <h2>Conclusion: Embracing Predictable Unpredictability</h2>
                        <p>By understanding the fundamental difference between the deterministic world of `Math.random()` and the secure, entropy-driven randomness of `crypto.getRandomValues()`, developers can make informed decisions and build better, safer, and more engaging applications.</p>
                        
                        <h2 id="faq">Frequently Asked Questions (FAQ)</h2>
                        <div className="space-y-4">
                            {faqData.map((item, index) => (
                                <div key={index}>
                                    <h3 className="font-semibold text-white">{item.question}</h3>
                                    <p>{item.answer}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
                <div className="text-center mt-6">
                    <button onClick={() => setIsExpanded(!isExpanded)} className="bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-700 hover:to-pink-700 text-white font-bold py-2 px-6 rounded-lg transition-all duration-300 transform hover:scale-105">
                        {isExpanded ? 'Read Less' : 'Read More...'}
                    </button>
                </div>
            </article>
        </section>
    );
};

export default SEOArticle;